### ISSUE TITLE
Add support for emission maps + bloom effect

### ISSUE THREAD

**Issue by mrDIMAS** [rg3dengine/rg3d#87]
Currently there is no way of marking surfaces as light emission surfaces. This can be easily fixed by adding additional map to each surface - emission map, it is a simple texture with 0..1 values where 0 - no emission, 1 - full bright. 

Possible solution:
1) Add emission texture field to Surface
2) Write emission value from emission map in GBuffer - there is exactly one `float` value left in ambient render target - `outAmbient.w`
3) Make separate render pass - Bloom (could be done similar to `fxaa.rs` - as it is just post-processing effect), frame buffer should be something around 1/3 size of screen render target.
4) Use Gbuffer's emission value in Bloom pass - write `diffuseColor * emissionValue` to the frame buffer.
5) Use Blur render pass to smooth final emission texture and render it in main render target.

**Comment by glowing-chemist** [comment]
I think just using an emission factor rather than a full float3 will be pretty limiting, most game assets (at least that I have encountered) have emission maps that vary from the albedo/diffuse in colour. Is there a reason you don't want to add more channels to the GBuffer? are there already bandwidth issues reading the gbuffer?

**Comment by mrDIMAS** [comment]
@glowing-chemist Sorry I missed your question 😬 . I finally got time to implement this, and I just put emission in ambient light channel of the G Buffer and it works perfectly.
